// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prn232Project.Data;

#nullable disable

namespace Prn232Project.Migrations
{
    [DbContext(typeof(CloneEbayDbContext))]
    [Migration("20251103011618_seeddata")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prn232Project.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("country");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullName");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("isDefault");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("street");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Address__3213E83FE283DFA1");

                    b.HasIndex("UserId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("BidTime")
                        .HasColumnType("datetime")
                        .HasColumnName("bidTime");

                    b.Property<int?>("BidderId")
                        .HasColumnType("int")
                        .HasColumnName("bidderId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.HasKey("Id")
                        .HasName("PK__Bid__3213E83F2651B77D");

                    b.HasIndex("BidderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Bid", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Category__3213E83F2EFB0A5B");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Toys & Hobbies"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Books & Media"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Art & Collectibles"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pet Supplies"
                        });
                });

            modelBuilder.Entity("Prn232Project.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discountPercent");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("endDate");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("int")
                        .HasColumnName("maxUsage");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("startDate");

                    b.HasKey("Id")
                        .HasName("PK__Coupon__3213E83F6B4E6588");

                    b.HasIndex("ProductId");

                    b.ToTable("Coupon", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Dispute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("RaisedBy")
                        .HasColumnType("int")
                        .HasColumnName("raisedBy");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Dispute__3213E83FA575F05B");

                    b.HasIndex("OrderId");

                    b.HasIndex("RaisedBy");

                    b.ToTable("Dispute", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("averageRating");

                    b.Property<decimal?>("PositiveRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("positiveRate");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.Property<int?>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("totalReviews");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3213E83FF0677904");

                    b.HasIndex("SellerId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("lastUpdated");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__Inventor__3213E83F5BA92A1D");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiverId");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("senderId");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("PK__Message__3213E83FBFBF0CE2");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("unitPrice");

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3213E83F085BA5C8");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.OrderTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("addressId");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("buyerId");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderDate");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totalPrice");

                    b.HasKey("Id")
                        .HasName("PK__OrderTab__3213E83F53068A32");

                    b.HasIndex("AddressId");

                    b.HasIndex("BuyerId");

                    b.ToTable("OrderTable", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("method");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime")
                        .HasColumnName("paidAt");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3213E83F3A68E03F");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuctionEndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("auctionEndTime");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.Property<bool?>("IsAuction")
                        .HasColumnType("bit")
                        .HasColumnName("isAuction");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Product__3213E83F5DB12984");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Brand new, unopened box. Official Apple warranty.",
                            Images = "https://example.com/images/iphone15.jpg",
                            IsAuction = false,
                            Price = 34990000m,
                            SellerId = 1,
                            Title = "iPhone 15 Pro Max 256GB"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Flagship Android phone, 12GB RAM, 512GB storage.",
                            Images = "https://example.com/images/s24ultra.jpg",
                            IsAuction = false,
                            Price = 28990000m,
                            SellerId = 1,
                            Title = "Samsung Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Classic white sneakers, size 42.",
                            Images = "https://example.com/images/airforce1.jpg",
                            IsAuction = false,
                            Price = 2500000m,
                            SellerId = 1,
                            Title = "Nike Air Force 1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Solid oak coffee table, modern style.",
                            Images = "https://example.com/images/coffeetable.jpg",
                            IsAuction = false,
                            Price = 1800000m,
                            SellerId = 1,
                            Title = "Wooden Coffee Table"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Brand new, collector’s edition set.",
                            Images = "https://example.com/images/lego-falcon.jpg",
                            IsAuction = false,
                            Price = 5500000m,
                            SellerId = 1,
                            Title = "Lego Star Wars Millennium Falcon"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "High-performance synthetic motor oil.",
                            Images = "https://example.com/images/mobil1.jpg",
                            IsAuction = false,
                            Price = 900000m,
                            SellerId = 1,
                            Title = "Mobil 1 Engine Oil 5W-30"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            Description = "Anti-aging moisturizer for daily use.",
                            Images = "https://example.com/images/loreal.jpg",
                            IsAuction = false,
                            Price = 450000m,
                            SellerId = 1,
                            Title = "L’Oreal Face Cream"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            Description = "Official size 5 match ball.",
                            Images = "https://example.com/images/adidasball.jpg",
                            IsAuction = false,
                            Price = 700000m,
                            SellerId = 1,
                            Title = "Adidas Football"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            Description = "All 7 books in a hardcover collection.",
                            Images = "https://example.com/images/harrypotter.jpg",
                            IsAuction = false,
                            Price = 950000m,
                            SellerId = 1,
                            Title = "Harry Potter Box Set"
                        },
                        new
                        {
                            Id = 10,
                            AuctionEndTime = new DateTime(2025, 11, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 9,
                            Description = "Original 1960s oil painting, framed.",
                            Images = "https://example.com/images/painting.jpg",
                            IsAuction = true,
                            Price = 8500000m,
                            SellerId = 1,
                            Title = "Vintage Painting"
                        });
                });

            modelBuilder.Entity("Prn232Project.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Prn232Project.Models.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__ReturnRe__3213E83F5992DCFD");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("ReturnRequest", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("reviewerId");

                    b.HasKey("Id")
                        .HasName("PK__Review__3213E83F89E1D570");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.ShippingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("carrier");

                    b.Property<DateTime?>("EstimatedArrival")
                        .HasColumnType("datetime")
                        .HasColumnName("estimatedArrival");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trackingNumber");

                    b.HasKey("Id")
                        .HasName("PK__Shipping__3213E83F85FA378C");

                    b.HasIndex("OrderId");

                    b.ToTable("ShippingInfo", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bannerImageURL");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.Property<string>("StoreName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("storeName");

                    b.HasKey("Id")
                        .HasName("PK__Store__3213E83F7A7A4E3D");

                    b.HasIndex("SellerId");

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("Prn232Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatarURL");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F558D5DB7");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164B92F732F")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://example.com/avatars/seller1.jpg",
                            Email = "seller1@example.com",
                            Password = "123456",
                            Role = "seller",
                            Username = "seller1"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://example.com/avatars/seller2.jpg",
                            Email = "seller2@example.com",
                            Password = "123456",
                            Role = "seller",
                            Username = "seller2"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://example.com/avatars/seller3.jpg",
                            Email = "seller3@example.com",
                            Password = "123456",
                            Role = "seller",
                            Username = "seller3"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "https://example.com/avatars/buyer1.jpg",
                            Email = "buyer1@example.com",
                            Password = "123456",
                            Role = "buyer",
                            Username = "buyer1"
                        },
                        new
                        {
                            Id = 5,
                            AvatarUrl = "https://example.com/avatars/buyer2.jpg",
                            Email = "buyer2@example.com",
                            Password = "123456",
                            Role = "buyer",
                            Username = "buyer2"
                        },
                        new
                        {
                            Id = 6,
                            AvatarUrl = "https://example.com/avatars/buyer3.jpg",
                            Email = "buyer3@example.com",
                            Password = "123456",
                            Role = "buyer",
                            Username = "buyer3"
                        },
                        new
                        {
                            Id = 7,
                            AvatarUrl = "https://example.com/avatars/buyer4.jpg",
                            Email = "buyer4@example.com",
                            Password = "123456",
                            Role = "buyer",
                            Username = "buyer4"
                        });
                });

            modelBuilder.Entity("Prn232Project.Models.Address", b =>
                {
                    b.HasOne("Prn232Project.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Address__userId__3A81B327");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn232Project.Models.Bid", b =>
                {
                    b.HasOne("Prn232Project.Models.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .HasConstraintName("FK__Bid__bidderId__5629CD9C");

                    b.HasOne("Prn232Project.Models.Product", "Product")
                        .WithMany("Bids")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Bid__productId__5535A963");

                    b.Navigation("Bidder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Prn232Project.Models.Coupon", b =>
                {
                    b.HasOne("Prn232Project.Models.Product", "Product")
                        .WithMany("Coupons")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Coupon__productI__60A75C0F");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Prn232Project.Models.Dispute", b =>
                {
                    b.HasOne("Prn232Project.Models.OrderTable", "Order")
                        .WithMany("Disputes")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Dispute__orderId__693CA210");

                    b.HasOne("Prn232Project.Models.User", "RaisedByNavigation")
                        .WithMany("Disputes")
                        .HasForeignKey("RaisedBy")
                        .HasConstraintName("FK__Dispute__raisedB__6A30C649");

                    b.Navigation("Order");

                    b.Navigation("RaisedByNavigation");
                });

            modelBuilder.Entity("Prn232Project.Models.Feedback", b =>
                {
                    b.HasOne("Prn232Project.Models.User", "Seller")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK__Feedback__seller__66603565");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Prn232Project.Models.Inventory", b =>
                {
                    b.HasOne("Prn232Project.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Inventory__produ__6383C8BA");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Prn232Project.Models.Message", b =>
                {
                    b.HasOne("Prn232Project.Models.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Message__receive__5DCAEF64");

                    b.HasOne("Prn232Project.Models.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Message__senderI__5CD6CB2B");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Prn232Project.Models.OrderItem", b =>
                {
                    b.HasOne("Prn232Project.Models.OrderTable", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderItem__order__46E78A0C");

                    b.HasOne("Prn232Project.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__OrderItem__produ__47DBAE45");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Prn232Project.Models.OrderTable", b =>
                {
                    b.HasOne("Prn232Project.Models.Address", "Address")
                        .WithMany("OrderTables")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__OrderTabl__addre__440B1D61");

                    b.HasOne("Prn232Project.Models.User", "Buyer")
                        .WithMany("OrderTables")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK__OrderTabl__buyer__4316F928");

                    b.Navigation("Address");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("Prn232Project.Models.Payment", b =>
                {
                    b.HasOne("Prn232Project.Models.OrderTable", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Payment__orderId__4AB81AF0");

                    b.HasOne("Prn232Project.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Payment__userId__4BAC3F29");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn232Project.Models.Product", b =>
                {
                    b.HasOne("Prn232Project.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Product__categor__3F466844");

                    b.HasOne("Prn232Project.Models.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK__Product__sellerI__403A8C7D");

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Prn232Project.Models.RefreshToken", b =>
                {
                    b.HasOne("Prn232Project.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn232Project.Models.ReturnRequest", b =>
                {
                    b.HasOne("Prn232Project.Models.OrderTable", "Order")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__ReturnReq__order__5165187F");

                    b.HasOne("Prn232Project.Models.User", "User")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ReturnReq__userI__52593CB8");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prn232Project.Models.Review", b =>
                {
                    b.HasOne("Prn232Project.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Review__productI__59063A47");

                    b.HasOne("Prn232Project.Models.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FK__Review__reviewer__59FA5E80");

                    b.Navigation("Product");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Prn232Project.Models.ShippingInfo", b =>
                {
                    b.HasOne("Prn232Project.Models.OrderTable", "Order")
                        .WithMany("ShippingInfos")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__ShippingI__order__4E88ABD4");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Prn232Project.Models.Store", b =>
                {
                    b.HasOne("Prn232Project.Models.User", "Seller")
                        .WithMany("Stores")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK__Store__sellerId__6D0D32F4");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Prn232Project.Models.Address", b =>
                {
                    b.Navigation("OrderTables");
                });

            modelBuilder.Entity("Prn232Project.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Prn232Project.Models.OrderTable", b =>
                {
                    b.Navigation("Disputes");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("ReturnRequests");

                    b.Navigation("ShippingInfos");
                });

            modelBuilder.Entity("Prn232Project.Models.Product", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Coupons");

                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Prn232Project.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Bids");

                    b.Navigation("Disputes");

                    b.Navigation("Feedbacks");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("OrderTables");

                    b.Navigation("Payments");

                    b.Navigation("Products");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReturnRequests");

                    b.Navigation("Reviews");

                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
